apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-pod-chaos-monkey
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubernetes-pod-chaos-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-pod-chaos-monkey
    spec:
      containers:
      - name: kubernetes-pod-chaos-monkey
        image: patrocinio/kubernetes-pod-chaos-monkey
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          value: "ping-pong"
        - name: DELAY
          value: "30"

